### ISSUE TITLE
Not working for Official Score labelled sheets

### ISSUE THREAD

**Issue by Santanu29** [LibreScore/dl-librescore#10]
I used the CLI to download sheets. It is working great. But I have noticed that sheets labeled as official scores get stuck while downloading there is an error that occurs. 
The processing goes on forever and the file is not downloaded at all. Does the script only work for sheets labeled user scores only?

![image](https://user-images.githubusercontent.com/69161246/203617020-b9948488-0ebd-42a1-a6a9-07e908d36b97.png)

**Comment by sealsrock12** [comment]
Official scores can't be downloaded with the app or CLI. They can only be downloaded with the userscript and a Pro+ subscription.

Without the script, you can't download official scores at all, even with a Pro+ subscription.
