### ISSUE TITLE
midi files for official scores don't contain lyrics 

### ISSUE THREAD

**Issue by 8139david** [LibreScore/dl-librescore#11]
With a Pro+ account, I've downloaded midi files for some official scores (using the script).
These midi files contain the notes of the lyrics, but not the lyrics (text) themselves.

**Comment by sealsrock12** [comment]
I think this is because the conversion from mscz to midi that musescore.com does just doesn't convert lyrics

**Comment by 8139david** [comment]
Unfortunately, there is no way to get the mscz file either from the script or from the app.

**Comment by PeterNjeim** [comment]
Upstream issue: https://github.com/musescore/MuseScore/issues/15925
