### ISSUE TITLE
The app doesn't work

### ISSUE THREAD

**Issue by vicentantonn** [LibreScore/dl-librescore#25]
I need to download a .mscz sheet and I can't. It doesn't work, it stays charging and charging...

<img width="489" alt="image" src="https://github.com/LibreScore/dl-librescore/assets/68785339/276d89e2-4f94-44a3-9b8c-33a5fcf44b0b">

**Comment by PeterNjeim** [comment]
Wrong repository, LibreScore/app-librescore is for the app. Also, support requests are to be made in the Discord server, not GitHub
