### ISSUE TITLE
Create the file path if it does not exist (cli)

### ISSUE THREAD

**Issue by arashi-dev** [LibreScore/dl-librescore#27]
While using the CLI, I propose implementing a feature to automatically create the file path if it does not already exist during the download process. Additionally, incorporating a prompt to ask the user before creating the path would ensure that users have control over the path creation. This approach combines both the convenience of automatic path creation and the user's autonomy in the process.

**Comment by PeterNjeim** [comment]
PR's are welcome

**Comment by PeterNjeim** [comment]
Will release in the next update (automatically publishes every Sunday)
