### ISSUE TITLE
Download Buttons Stuck On Bottom Right Corner

### ISSUE THREAD

**Issue by poudink** [LibreScore/dl-librescore#3]
The download buttons don't seem to appear correctly. They work, but they're totally stuck at the bottom right corner of the screen, constantly hiding that part and pretty inconvenient. I took the screenshot below with uBlock Origin and Dark Reader enabled, but this happens regardless of whether other extensions are enabled, so it can't be interference.

I've observed this issue with:
Violentmonkey, Firefox, Linux
Tampermonkey, Firefox, Linux
Violentmonkey, Opera, Windows 7
Violentmonkey, Opera GX, Windows 10

I also tried Firemonkey and Greasemonkey just in case, but the userscript didn't work at all there.

I know for a fact this used to work fine a long time ago (it's probably been a couple of years at this point) and would place the download buttons below the Share/Add to set buttons. It just suddenly broke one day and I didn't think to open an issue until now.
![image](https://user-images.githubusercontent.com/29778535/162115181-35671af2-202d-4b10-8341-453dcfe1386d.png)

**Comment by PeterNjeim** [comment]
Bottom right corner, not left, but the reason they're anchored now is to avoid Musescore's detection. This has been the case for over a year now. It shouldn't block anything, sometimes there are even two scroll bars (if the browser width is small enough) to make sure you can reach everything you need.

**Comment by PeterNjeim** [comment]
If you mean you want a dark mode version of it to not blind your eyes (since dark reader can't do it as it's anchored and rendered after the initial page render), then I could probably do it at a later time

**Comment by Xmader** [comment]
> it's anchored and rendered after the initial page render

There should be an easy fix. I've worked on it before, but I don't if anything changes.

**Comment by DereC4** [comment]
In my opinion, an acceptable cosmetic loss for an awesome downloader!

**Comment by DereC4** [comment]
In my opinion, an acceptable cosmetic loss for an awesome downloader!

**Comment by DereC4** [comment]
I'm wondering how this would be fixed though; looks like right now it's more of an overlay in the user screen than embedded into site html

**Comment by PeterNjeim** [comment]
Fixed in df36815a2b26271d4f9a56d3a2636ac671112dd2. Update to [v0.35.20](https://github.com/LibreScore/dl-librescore/releases/tag/v0.35.20)
