### ISSUE TITLE
Popup blocker causes MIDI and MP3 downloads to fail

### ISSUE THREAD

**Issue by 0bsidianFox** [LibreScore/dl-librescore#34]
using this with TamperMonkey (first time user), I'm trying to download [This](https://musescore.com/user/34004011/scores/6904326) but it does nothing.

**Comment by 0bsidianFox** [comment]
It also doesn't download mp3, PDF works, although, those are not what I want.

**Comment by PeterNjeim** [comment]
Cannot reproduce, MIDI, MP3 and PDF all work for me. Though, you are the 3rd person to report an error with MIDI downloads (the other two on Discord). Maybe MuseScore is doing an A/B test and changed how its player works.

Please share your dl-librescore version (from the Tampermonkey Dashboard. See if there are any relevant errors in the browser console (there are many MuseScore errors, don't share those, try to see if there are any produced by the script itself)

**Comment by 0bsidianFox** [comment]
> Cannot reproduce, MIDI, MP3 and PDF all work for me. Though, you are the 3rd person to report an error with MIDI downloads (the other two on Discord). Maybe MuseScore is doing an A/B test and changed how its player works.
> 
> Please share your dl-librescore version (from the Tampermonkey Dashboard. See if there are any relevant errors in the browser console (there are many MuseScore errors, don't share those, try to see if there are any produced by the script itself)

The version is 0.34.49,

IDK, the only thing i could find was in the issues tab and not in the console since where it actually show something when i [ress the button, see the image:
![image](https://github.com/LibreScore/dl-librescore/assets/72424605/31d84fad-b04f-41ca-82f2-80ca13b35861)

IDK if that will help...

**Comment by PeterNjeim** [comment]
Basically, open the Console, then refresh the page, then click the circle with a slash icon in the top bar of the console to clear it. Then click on Download MIDI and see if any errors appear. Make sure your Console visibility settings are set to show errors (they show errors by default)

**Comment by 0bsidianFox** [comment]
the console does not list anything after following the exact steps. 
![image](https://github.com/LibreScore/dl-librescore/assets/72424605/d1934299-4288-4c8e-9842-be1925a83d9f)

**Comment by 0bsidianFox** [comment]
Fixed the problem, it had something to do with one of these:
![image](https://github.com/LibreScore/dl-librescore/assets/72424605/f19a73aa-dafc-4ce9-b350-68977e99860e)
Either Malwarebytes or AdBlocker Ultimate or poper blocker
I disabled them all so IDK which one was causing it specifically.
