### ISSUE TITLE
Network error when trying to download

### ISSUE THREAD

**Issue by nhussain22** [LibreScore/dl-librescore#4]
Samsung S7 edge. Trying to download score: https://musescore.com/user/15454861/scores/7592423
Successfully download a mscz before, but downloading this throws a network error?

**Comment by SealsRock12** [comment]
Wrong repo, this is for the userscript not the app.

Also, this is not a bug. Support is provided in the [Discord server](https://discord.gg/DKu7cUZ4XQ).
