### ISSUE TITLE
got IP banned for scripted downloading too many scores

### ISSUE THREAD

**Issue by corn-nut-birdie** [LibreScore/dl-librescore#5]
Using a Shell for-loop from a scores URL list file, downloaded hundreds of scores in a short time. The script and the browser website works fine for that while. Then suddenly the IP got banned. It returned 403 from both command line and the browser. 

some blog about "web crawler" from search results said that, downloading too many data or requesting too often in a short time, would get IP banned.

I haven't found the right request interval, or data amount threshold. Could anybody point out that ?

**Comment by SealsRock12** [comment]
Were you rate-limited or just IP-banned? If you were actually IP-banned, it was probably manual (or at least not on an interval).

**Comment by corn-nut-birdie** [comment]
> Were you rate-limited or just IP-banned? If you were actually IP-banned, it was probably manual (or at least not on an interval).

Some previous mate said that, once working, there was anti data crawler mechanism in a data center, that prohibited his web program working as expected, which was adjusted then, according to his request.

**Comment by PeterNjeim** [comment]
MuseScore has a rate-limit in place, you'll be unbanned in 24 hours at most

**Comment by rghavimi** [comment]
<img width="1486" alt="Screenshot 2024-12-05 at 10 07 17 PM" src="https://github.com/user-attachments/assets/67d222bf-a476-4652-9295-cb930dcf2693">

I believe I'm coming across a similar issue using dl-librescore@0.35.19 . When running a command-line tool on a Heroku dyno, the initial request to MuseScore succeeds, but subsequent attempts fail after a short interval. The tool returns "Score not found," suggesting that MuseScore may be blocking requests originating from Heroku IP addresses. Running the same tool locally does not produce the same issue.

Curious if you have any ideas @PeterNjeim
