### ISSUE TITLE
Command line PDF download error

### ISSUE THREAD

**Issue by micheldebree** [LibreScore/dl-librescore#50]
- ```npx dl-librescore@latest```
- url: `https://musescore.com/user/953676/scores/9731629`
- Select PDF
- Use default output folder
- error:

```
Processing…/Users/michel/.npm/_npx/47461c73a56e4a1f/node_modules/dl-librescore/dist/cli.js:4711
    return info.url;
                ^

TypeError: Cannot read properties of null (reading 'url')
    at /Users/michel/.npm/_npx/47461c73a56e4a1f/node_modules/dl-librescore/dist/cli.js:4711:17
    at Generator.next (<anonymous>)
    at fulfilled (/Users/michel/.npm/_npx/47461c73a56e4a1f/node_modules/dl-librescore/dist/cli.js:17:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Did some quick debugging; the `info` is destructured from the json that is returned. That doesn't contain an `info` property, but it does contain a 404 error.

**Comment by PeterNjeim** [comment]
Command-line tool isn't working right now, see https://github.com/LibreScore/dl-librescore/issues/44
