### ISSUE TITLE
Midi Downloading not working (User Script)

### ISSUE THREAD

**Issue by Wreyth** [LibreScore/dl-librescore#51]
Was working yesterday albeit had to refresh the page a couple times to get it to download a midi from musescore, today can't get any to download. Clicked the download midi option and it just says processing for a couple seconds then nothing. 

Using the tampermonkey with user script option

**Comment by stfu23489** [comment]
same issue

**Comment by PeterNjeim** [comment]
I think it's a MuseScore issue

**Comment by KneesDev** [comment]
It is a MuseScore issue. Run the JavaScript line in the console and then press one of the 3 download buttons. It's a timeout issue, but there's authentication errors below so I believe it's MuseScore rejecting the request due to authentication missing.

**Comment by PeterNjeim** [comment]
MuseScore has resolved their issue

**Comment by PeterNjeim** [comment]
MuseScore is broken again. Easiest way to tell is if only the first page loads

**Comment by PeterNjeim** [comment]
MuseScore has resolved their issue again
