### ISSUE TITLE
Download options not showing up

### ISSUE THREAD

**Issue by MIDMan24** [LibreScore/dl-librescore#53]
I used to use this a lot, but for some reason the download options don't appear at the bottom. So what do I do?

**Comment by PeterNjeim** [comment]
If you're on mobile you need to enable desktop mode. The buttons might be stuck at the very bottom of the page, requiring you to scroll down in the right pane.

If you're on desktop, you might need to make your browser window wider, or zoom out of that's not possible.

Need more details to help you, such as the song you're trying to download, what device you're using, what method you're using to run the script, etc.
