### ISSUE TITLE
Trying to download pdf with node error

### ISSUE THREAD

**Issue by DereC4** [LibreScore/dl-librescore#54]
- Processing…node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "function Error() { [native code] }".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v18.17.0

The script wasn't working on tampermonkey so I tried using node and it failed similarly

**Comment by PeterNjeim** [comment]
Duplicate of https://github.com/LibreScore/dl-librescore/issues/44. Can't reproduce Tampermonkey issue, make a new issue detailing your problem
