### ISSUE TITLE
How to use command-line tool with Tor or a http proxy ?

### ISSUE THREAD

**Issue by corn-nut-birdie** [LibreScore/dl-librescore#6]
As the title, how to use command-line tool with Tor or a http proxy ?
The country has some network censoring, and many foreign sites / IP could not be accessed. As well as `dl-librescore` often throw network error by direct network access.

Tried NPM config set proxy / https-proxy, Shell export proxy / https_proxy, and Windows network proxy. All does not make the access normally.

**Comment by SealsRock12** [comment]
We don't have any support for that at the time, nor are we planning on adding it. But you could try [ProxyCap](https://www.proxycap.com/), it has worked for me for applications in the past.

**Comment by Xmader** [comment]
As a Chinese myself, I totally understand what you're asking for.

**Comment by Xmader** [comment]
Support added in `v0.34.41`.

You can now set the `HTTPS_PROXY` environment variable to use proxy.

```sh
HTTPS_PROXY=http://host:port npx dl-librescore@latest
```
