### ISSUE TITLE
bug: CLI can't download MIDI files

### ISSUE THREAD

**Issue by TheAfroOfDoom** [LibreScore/dl-librescore#61]
Verified with `git bisect` that this was broken by commit https://github.com/LibreScore/dl-librescore/commit/772e7b37a13c93244077149c3c24378ac0099d86

Still works for me on commit fc99d7fd9b32f0eeaec79a657268f6060bdb341b

---

## This is duplicated by:

https://github.com/LibreScore/dl-librescore/issues/60

---

It'd be nice if the errors had actual error messages instead of being `throw Error`. It's unclear right now that the CLI knowingly doesn't support downloading MIDI files.

See:

| `throw new Error("Unimplemented");` | `throw Error;` |
|-|-|
| <img alt="" src="https://github.com/LibreScore/dl-librescore/assets/13565346/f684dd25-2454-4f96-86d7-b24e9df1b500" width=1000 /> | <img alt="" src="https://github.com/LibreScore/dl-librescore/assets/13565346/9955013b-a57b-4456-b0f9-078b5857c2fc" width=800 /> |

**Comment by PeterNjeim** [comment]
By "still working for me" do you mean you get the `TypeError: Cannot read properties of null (reading 'url')` error?

**Comment by TheAfroOfDoom** [comment]
> By "still working for me" do you mean you get the `TypeError: Cannot read properties of null (reading 'url')` error?

Yes, _but_ the PDF was still being saved to disk despite the error? it may have only been the first page that was being saved now that I think about it

**Comment by TheAfroOfDoom** [comment]
entirely possible this could be considered a duplicate of https://github.com/LibreScore/dl-librescore/issues/44

**Comment by PeterNjeim** [comment]
That's what I was going to say. The reason the error is a different message is because I made it fail since I wasn't able to get the authorization token due to Cloudflare's bot detection (see: https://github.com/LibreScore/dl-librescore/blob/772e7b37a13c93244077149c3c24378ac0099d86/src/file.ts#L17-L20)
