### ISSUE TITLE
Some files have no file extensions

### ISSUE THREAD

**Issue by AxiealAeon** [LibreScore/dl-librescore#63]
whenever I have clicked download, I get this file.
I am a music student and I have found this quite troublesome.

![image](https://github.com/LibreScore/dl-librescore/assets/167269638/0c8ebcf8-3b96-4010-8b73-9d93bae99d10)

Thank you for your work you legends

**Comment by PeterNjeim** [comment]
In this case the file downloads are working. It's simply the file name that is broken. Please rename the file to anything you want, and put `.mid` at the end. Usually the file name is removed when there are illegal characters for the Windows file explorer, but there's a bug in the program that forgets to add a period when this happens, so the file has no file extension. I'll fix this bug, but in the meantime change the file name manually

**Comment by PeterNjeim** [comment]
@AxiealAeon Can you give me the URL to a song that has this issue? I need it to diagnose the issue

**Comment by AxiealAeon** [comment]
> @AxiealAeon Can you give me the URL to a song that has this issue? I need it to diagnose the issue

here, thanks for the help mate!!

https://musescore.com/user/48274920/scores/11835760

**Comment by AxiealAeon** [comment]
> In this case the file downloads are working. It's simply the file name that is broken. Please rename the file to anything you want, and put `.mid` at the end. Usually the file name is removed when there are illegal characters for the Windows file explorer, but there's a bug in the program that forgets to add a period when this happens, so the file has no file extension. I'll fix this bug, but in the meantime change the file name manually

Holy Origin! it worked!

**Comment by PeterNjeim** [comment]
Fixed in df36815a2b26271d4f9a56d3a2636ac671112dd2. Update to [v0.35.20](https://github.com/LibreScore/dl-librescore/releases/tag/v0.35.20)
