### ISSUE TITLE
Can't download .MSCZ files

### ISSUE THREAD

**Issue by ChithilaW** [LibreScore/dl-librescore#69]
I downloaded the Liberscore App and tried to covert [Pirates Of The Caribbean](https://musescore.com/user/4841481/scores/9412102). But it gave an error when I tried to download the file.

P.S. 
  This is my first time reporting an issue/bug here so please tell me if I'm doing something wrong

**Comment by PeterNjeim** [comment]
Wrong repository, duplicate of https://github.com/LibreScore/dl-librescore/issues/4
