### ISSUE TITLE
Download buttons won't show until entering the inspect element tool

### ISSUE THREAD

**Issue by Mikemin291** [LibreScore/dl-librescore#76]

**Comment by PeterNjeim** [comment]
Can't reproduce. Share more details about your browser, extension version, score being viewed, etc.

**Comment by PeterNjeim** [comment]
Fixed in df36815a2b26271d4f9a56d3a2636ac671112dd2. Update to [v0.35.20](https://github.com/LibreScore/dl-librescore/releases/tag/v0.35.20)
