### ISSUE TITLE
Browser Extension Downloads Only One Page

### ISSUE THREAD

**Issue by fonky415** [LibreScore/dl-librescore#78]
Are scores like [this](https://musescore.com/user/39593079/scores/16198786) just not accessible because preview ends in one page? Or must I use command line to download PDF?

**Comment by blade2005** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by PeterNjeim** [comment]
Duplicate of https://github.com/LibreScore/dl-librescore/issues/10
