### ISSUE TITLE
Browser extension doesn't work

### ISSUE THREAD

**Issue by JChrysanthemum** [LibreScore/dl-librescore#80]
Environment: WIN10 + Edege

Version: dl-librescore 0.35.15 - 0.35.19 not works.

I tried dl-librescore on musescore a month ago, it works amazing.
But it failed and showed nothing today. 
Any idea for this? How could I get more information from Edge?

Many thanks

**Comment by PeterNjeim** [comment]
Give me a screenshot of the popup menu that appears when you click on the Tampermonkey extension icon when viewing a song on musescore.com

**Comment by JChrysanthemum** [comment]
@PeterNjeim 

Sorry for my carelessness, it seems that the extension disabled all scripts before. 

Thanks a lot for your time and I will close this issue.
