### ISSUE TITLE
Community Score Not Found

### ISSUE THREAD

**Issue by alinrdinn** [LibreScore/dl-librescore#81]
https://musescore.com/user/34441205/scores/6138829

using those url, the command prompt cannot find the score

![image](https://github.com/user-attachments/assets/b7b252d1-237a-400b-9b3d-2c49373e993d)

**Comment by alinrdinn** [comment]
Actually, ALL the community score cannot be downloaded.

**Comment by PeterNjeim** [comment]
Cannot reproduce

![image](https://github.com/user-attachments/assets/55f1cd52-8a1a-46ae-b781-1a00a9bbe46a)

**Comment by PeterNjeim** [comment]
@alinrdinn Can you test it again to see if it was a temporary issue? If it still fails, can you try using a VPN to another country to see if it works? If that still fails, it could be due to an A/B test on musescore.com, in which case I'll have to do more testing

**Comment by alinrdinn** [comment]
I tested again and it works. I can confirm it is temporary issue but do not know why.
