### ISSUE TITLE
help

### ISSUE THREAD

**Issue by dogecoder1311** [LibreScore/dl-librescore#85]
when im using the command line tool it shows up with this 

npm error code ENOENT
npm error syscall lstat
npm error path C:\Users\Admin\AppData\Roaming\npm
npm error errno -4058
npm error enoent ENOENT: no such file or directory, lstat 'C:\Users\Admin\AppData\Roaming\npm'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: C:\Users\Admin\AppData\Local\npm-cache\_logs\2024-10-20T03_16_32_413Z-debug-0.log

**Comment by PeterNjeim** [comment]
1. Open File Explorer
2. In the URL bar, type `%appdata%` and press `Enter ↵`
3. Create a new folder and name it `npm`
