### ISSUE TITLE
Firefox Android download buttons cover play button

### ISSUE THREAD

**Issue by terrysfood** [LibreScore/dl-librescore#86]
On Firefox Android, the buttons added on the page cover the play button. Allow for the buttons to not obscure the play button or embed the buttons into the page to avoid obscuring page details.

<img src="https://github.com/user-attachments/assets/8f2f5501-5128-4f43-b523-01ac1f4a3f00" width="256" alt="Screenshot_20241029_193753_Firefox"> <img src="https://github.com/user-attachments/assets/e297efcd-f031-4134-9298-9d3227a9f2c5" width="256" alt="Screenshot_20241029_193839_Firefox">
First image is with uBlock Origin enabled, second with it disabled

**Comment by PeterNjeim** [comment]
They used to be embedded into the page, though that was [detectable by MuseScore](https://github.com/Xmader/musescore-downloader/issues/95). So we switched to a post-load injection method, which anchors the buttons on the screen. I could add a button to minimize the buttons temporarily, or add an option in the Tampermonkey menu to disable the onscreen buttons (the download buttons are always available in the Tampermonkey menu)

**Comment by PeterNjeim** [comment]
Fixed in df36815a2b26271d4f9a56d3a2636ac671112dd2. Update to [v0.35.20](https://github.com/LibreScore/dl-librescore/releases/tag/v0.35.20)
