### ISSUE TITLE
Suggestion: use `bottom: 0` instead of dynamically calculated `top:`

### ISSUE THREAD

**Issue by denilsonsa** [LibreScore/dl-librescore#87]
The current behavior will calculate the top position based on some element bounding box and the current scroll position:
https://github.com/LibreScore/dl-librescore/blob/990bf7997d1c4fe07bfb759691bf8aede1f9e68f/src/btn.ts#L150-L156

If the Userscript was executed while the page loaded in the background, the dimensions may not have been calculated correctly. If the user resizes the window, the position will be stuck in the wrong location. Scrolling might cause buggy positioning.

1. Remove the dynamic calculation
2. Add `bottom: 0;` to this div:
https://github.com/LibreScore/dl-librescore/blob/990bf7997d1c4fe07bfb759691bf8aede1f9e68f/src/btn.css#L1

This might fix #76

**Comment by PeterNjeim** [comment]
Fixed in df36815a2b26271d4f9a56d3a2636ac671112dd2. Update to [v0.35.20](https://github.com/LibreScore/dl-librescore/releases/tag/v0.35.20)
