### ISSUE TITLE
Script have stopped working.

### ISSUE THREAD

**Issue by ETO-QSH** [LibreScore/dl-librescore#88]
![image](https://github.com/user-attachments/assets/e8e5df95-4159-4109-be35-443dc4094b12)
This script seems to have stopped working. When I look at the score now, he doesn't give me a download button anywhere on the site as he did before. It seems to me that it stopped working in the last two days.
![image](https://github.com/user-attachments/assets/9a755a56-6ff6-4cc1-a09d-5b7d8f668cd5)
I'm sure I'm using the latest version and there don't seem to be any errors in the console. Are the buttons hidden? Please tell me what I should do.

**Comment by PeterNjeim** [comment]
Fixed in df36815a2b26271d4f9a56d3a2636ac671112dd2. Update to [v0.35.20](https://github.com/LibreScore/dl-librescore/releases/tag/v0.35.20)
