### ISSUE TITLE
Add note to old repository that it was moved

### ISSUE THREAD

**Issue by Glitchy-Tozier** [LibreScore/dl-librescore#9]
The old repo (https://github.com/Xmader/musescore-downloader) still shows up first in many search results, which is how I found it. Only after visiting some issues, I found out that the project had moved.

If possible, please add a prominent note to the beginning of the old repo's README that the old project has migrated here.

**Comment by sealsrock12** [comment]
Unfortunately, we don't have control over that repository. Only Xmader does, who hasn't communicated with us for around a year at this point.

**Comment by Glitchy-Tozier** [comment]
I see, that's unfortunate!

**Comment by LakesideMiners** [comment]
update that this has been fixed as there is now a link to it in that repo
