### ISSUE TITLE
Seeing a DeprecationWarning after updating powershell and node.js

### ISSUE THREAD

**Issue by wrendarkcloud** [LibreScore/dl-librescore#91]
Recently updated my powershell to version 7.4.6 and node.js to version 22.12.0

This warning pops up when I do npx dl-librescore which is version 0.35.20 at the moment

(node:17584) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

The application still works, but just wanted to report the warning I am seeing here. Thank you.

**Comment by PeterNjeim** [comment]
Fixed, will release this update in the future alongside other changes
